language: r
r:
  - release
os:
  - linux
  - osx
branches:
  only:
    master
    
r_github_packages:
  - IRSN/DiceKriging
r_packages:
  - rgenoud
  - foreach
  - doParallel
  - testthat
  - numDeriv
  - covr
cache: packages
    
addons:
  apt:
    packages:
      - libssh2-1-dev
      
before_install:
  - echo "$TRAVIS_OS_NAME"
  - echo "$TRAVIS_R_VERSION_STRING"
  - echo $PKG_TARBALL
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo chown -R $(whoami) /usr/local ; brew install libgit2; fi
  
after_success:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov()'; fi
  
before_deploy:
  - if [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then git tag "$TRAVIS_OS_NAME" --force; fi
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi

deploy:
  provider: releases
  name: "$TRAVIS_OS_NAME"
  api_key:
    secure: FAgknpCiXLcMqURSU5b045Z/6mEioXwpP02LQpUBH1aYMizXuHLIe9Qn7HZy6BeCIjp+UadAjZvJ7rJU52DKMMeKhKg0Moq9d4iENeISunVkgTu7siy42LheOJ2Y+ToS1XFHesm2qtCt+TQ5oDIaLFXApSzLEKu2td0H7wD+4scXFdalBvnd+q+3oXk0AYIIdhsMMBwXr4A0mXtsLSjVvrnyqEODIkXeu5sGezbXsdOLOu6CvlIFqqnWQRYf9iiaLVab8moJiQ1BogQNuCTpxWDCA2Yhu9njX6bAoBeVm1rM6nNF+vtWfSuAaBWJcdVbpOOs5mDIj+gQGg4z8N/XJIrVHs7WPU//+fUonxgIv549ToWwZ4MW0kIEyfDeUu51GJI6d99SsLGXvc/gVEzhSEG5gvGqDZWIHgyXgv66pxoaxvEi+3qHYXw7ijoAIkf/4Bzu1fjga2ypBzLH5gI9qE2aDqVMIgeONZW8zTeB8UU/3Fa6QKs8ruQtOhwNuN2X0dFhqMDEnciVBz2WW+JAlwbPm9V6CLDs+gnoiy/dMDrr9d4Sbc/U6btdQpJR2E6EnA8MsizJFvVEjIUypOPN2vjZWvXRdMUpu6kj8V9xUWXOu5fM8e19H78qvJcVlbAzBWdSXv/YR2otoQ+Scndi8p13FmrDfaI7CRcBwgJsJQY=
  file_glob: true
  file: RobustInv*.t*gz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    except: windows
    condition: "$TRAVIS_R_VERSION_STRING = release"
