// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// phi
arma::vec phi(arma::vec myarg);
RcppExport SEXP _RobustInv_phi(SEXP myargSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type myarg(myargSEXP);
    rcpp_result_gen = Rcpp::wrap(phi(myarg));
    return rcpp_result_gen;
END_RCPP
}
// fast_suroptinv
arma::vec fast_suroptinv(const long N, const long p, const long nsimu, const arma::mat& allsimu, const arma::mat& allsimu_centered, const arma::mat& kn, const arma::mat& allKninv, const arma::mat& lambda, const double mn, const double sn, const double T, const arma::mat& randmatrix);
RcppExport SEXP _RobustInv_fast_suroptinv(SEXP NSEXP, SEXP pSEXP, SEXP nsimuSEXP, SEXP allsimuSEXP, SEXP allsimu_centeredSEXP, SEXP knSEXP, SEXP allKninvSEXP, SEXP lambdaSEXP, SEXP mnSEXP, SEXP snSEXP, SEXP TSEXP, SEXP randmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const long >::type N(NSEXP);
    Rcpp::traits::input_parameter< const long >::type p(pSEXP);
    Rcpp::traits::input_parameter< const long >::type nsimu(nsimuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type allsimu(allsimuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type allsimu_centered(allsimu_centeredSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kn(knSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type allKninv(allKninvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type mn(mnSEXP);
    Rcpp::traits::input_parameter< const double >::type sn(snSEXP);
    Rcpp::traits::input_parameter< const double >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type randmatrix(randmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_suroptinv(N, p, nsimu, allsimu, allsimu_centered, kn, allKninv, lambda, mn, sn, T, randmatrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RobustInv_phi", (DL_FUNC) &_RobustInv_phi, 1},
    {"_RobustInv_fast_suroptinv", (DL_FUNC) &_RobustInv_fast_suroptinv, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_RobustInv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
