// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// phi
arma::vec phi(arma::vec myarg);
RcppExport SEXP RobustInv_phi(SEXP myargSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type myarg(myargSEXP);
    __result = Rcpp::wrap(phi(myarg));
    return __result;
END_RCPP
}
// fast_suroptinv
arma::vec fast_suroptinv(const long N, const long p, const long nsimu, const arma::mat& allsimu, const arma::mat& allsimu_centered, const arma::mat& kn, const arma::mat& allKninv, const arma::mat& lambda, const double mn, const double sn, const double T, const arma::mat& randmatrix);
RcppExport SEXP RobustInv_fast_suroptinv(SEXP NSEXP, SEXP pSEXP, SEXP nsimuSEXP, SEXP allsimuSEXP, SEXP allsimu_centeredSEXP, SEXP knSEXP, SEXP allKninvSEXP, SEXP lambdaSEXP, SEXP mnSEXP, SEXP snSEXP, SEXP TSEXP, SEXP randmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const long >::type N(NSEXP);
    Rcpp::traits::input_parameter< const long >::type p(pSEXP);
    Rcpp::traits::input_parameter< const long >::type nsimu(nsimuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type allsimu(allsimuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type allsimu_centered(allsimu_centeredSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kn(knSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type allKninv(allKninvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type mn(mnSEXP);
    Rcpp::traits::input_parameter< const double >::type sn(snSEXP);
    Rcpp::traits::input_parameter< const double >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type randmatrix(randmatrixSEXP);
    __result = Rcpp::wrap(fast_suroptinv(N, p, nsimu, allsimu, allsimu_centered, kn, allKninv, lambda, mn, sn, T, randmatrix));
    return __result;
END_RCPP
}
