# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phi <- function(myarg) {
    .Call('_RobustInv_phi', PACKAGE = 'RobustInv', myarg)
}

fast_suroptinv <- function(N, p, nsimu, allsimu, allsimu_centered, kn, allKninv, lambda, mn, sn, T, randmatrix) {
    .Call('_RobustInv_fast_suroptinv', PACKAGE = 'RobustInv', N, p, nsimu, allsimu, allsimu_centered, kn, allKninv, lambda, mn, sn, T, randmatrix)
}

