# This file was generated by Rcpp::compileAttributes
# 
# Make sure to save the comments before re-using Rcpp::compileAttributes
# since they will be removed !

phi <- function(myarg) {
    .Call('RobustInv_phi', PACKAGE = 'RobustInv', myarg)
}

#' @title Fast C++ computation of the surnew criterion
#' @description Computes the expectation of pn+1 (1 - pn+1) for all integration points 
#' using an update formula on Gaussian process conditional realizations. This is a 
#' crucial step for computing the surnew criterion.
#'   
#' @param N Number of integration points. 
#' @param p Number of simulation points. 
#' @param nsimu Number of conditional simulations per integration points. 
#' @param allsimu p x (nsimu*N) matrix where p is the number of simulation points. 
#' @param allsimu_centered p x (nsimu*N) matrix containing the later simulations centered by 
#' substracting the kriging mean of the points where the simulations are performed.
#' @param kn p x N matrix containing the kriging covariances between the candidate 
#' point x and all the p*N simulation points. 
#' @param allKninv (N*p) x p matrix containing N different p x p matrices. Matrix number i is the inverse 
#' of the p x p non-conditional covariance matrix of the p simulation points associated to the 
#' integration point i.
#' @param lambda p x N matrix of kriging weights of the candidate point x for the prediction in the simulation points. 
#' @param mn Kriging mean in the candidate point x
#' @param sn Kriging standard deviation in the candidate point x
#' @param T Target threshold.
#' @param randmatrix N x nsimu matrix containing independent realizations of a standard gaussian random variable.
#' @return A column vector of size N containing the expectation of pn+1 (1 - pn+1) for 
#' all the N integration points. The surnew criterion is simply the average (or weighted average - using the integration weights) 
#' of this array.
#' @author Clement Chevalier \email{clement.chevalier@@unine.ch}
#' @useDynLib RobustInv
#' @export
#' @examples 
#' 
#' library(KrigInv)
#' myfun <- branin_robinv
#' d <- 3
#' 
#' set.seed(8)
#' 
#' n0 <- 30
#' T <- 10
#' opt.index <- c(3)
#' inv.index <- c(1,2)
#' lower <- rep(0,times=d)
#' upper <- rep(1,times=d)
#' 
#' design <- matrix(runif(d*n0),nrow=n0)
#' response <- myfun(design)
#' model <- km(formula = ~1,design = design,response = response,covtype = "matern3_2")
#' 
#' n <- 20 ;p <- 50; nsimu <- 1000
#' 
#' integcontrol <- list(distrib = "surnew",n.points = n,finaldistrib="surnew",
#'                      n.candidates=50,nsimu=nsimu,n.optpoints = p,
#'                      choose_optpoints=TRUE,n.optpoints.candidates=500)
#' \dontrun{
#' obj <- integration_design_robinv(integcontrol = integcontrol,d=d,lower=lower,upper=upper,
#'                                  opt.index=opt.index,inv.index=inv.index,model=model,T=T)
#' 
#' randmatrix <- matrix(rnorm(nsimu*n),nrow=n)
#' current.sur <- sum(obj$integration.weights*obj$pn*(1-obj$pn))
#' 
#' x <- c(0.841295 , 0.0757517 , 0.7507468)
#' 
#' N <- n
#' n <- model@@n
#' xnew <- matrix(x,nrow=1)
#' pred <- predict_nobias_km(object=model,newdata=xnew,type="UK",checkNames=FALSE)
#' mn <- pred$mean ; sn <- pred$sd ; F.newdata <- pred$F.newdata ; c.newdata <- pred$c
#' 
#' kn_xnplus1_simupoints <- computeQuickKrigcov(model=model,integration.points=obj$allsimupoints,
#'                                              X.new=xnew,precalc.data=obj$allprecomp ,F.newdata=F.newdata ,c.newdata=c.newdata )
#' kn_xnplus1_simupoints <- matrix(kn_xnplus1_simupoints,nrow=p,ncol=N)
#' lambda <- kn_xnplus1_simupoints/sn^2
#' 
#' result  <- fast_suroptinv(N=N,p=p,nsimu=nsimu,allsimu=obj$allsimu,
#'                           allsimu_centered=obj$allsimucentered,
#'                           kn=kn_xnplus1_simupoints,allKninv=obj$allKn.inv,
#'                           lambda=lambda,mn=mn,sn=sn,T=T,
#'                           randmatrix=randmatrix)
#' 
#' result
#' sum(result*obj$integration.weights) # value of the surnew criterion at point x
#' }
fast_suroptinv <- function(N, p, nsimu, allsimu, allsimu_centered, kn, allKninv, lambda, mn, sn, T, randmatrix) {
    .Call('RobustInv_fast_suroptinv', PACKAGE = 'RobustInv', N, p, nsimu, allsimu, allsimu_centered, kn, allKninv, lambda, mn, sn, T, randmatrix)
}
